config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  root 'home#index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to friend_url(@friend), notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy

    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Not authorized to edit this Friend" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this crud from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3" style="font-family: Varela Round; width: 500px">
    <%= form.text_field :first_name,  class: "form-control", placeholder: "First Name" %>
  </div>

  <div class="mb-3" style="font-family: Varela Round; width: 500px">
    <%= form.text_field :last_name, class: "form-control", placeholder: "Last Name" %>
  </div>

  <div class="mb-3" style="font-family: Varela Round; width: 500px">
    <%= form.text_field :email, class: "form-control", placeholder: "Email" %>
  </div>

  <div class="mb-3" style="font-family: Varela Round; width: 500px">
    <%= form.text_field :phone, class: "form-control", placeholder: "Phone" %>
  </div>

  <div class="mb-3">
    <%= form.number_field :user_id, id: :friend_user_id, class: "form-control", value: current_user.id, type: :hidden %>
  </div>

  <br/>
  <div style="font-family: Varela Round;">
    <%= form.submit class: 'btn btn-success'%>
  </div>
<% end %>

app/views/friends/_friend.html.erb
<div id="<%= dom_id friend %>">
  <p>
    <strong>First name:</strong>
    <%= friend.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= friend.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= friend.email %>
  </p>

  <p>
    <strong>Phone:</strong>
    <%= friend.phone %>
  </p>

</div>

app/views/friends/edit.html.erb
<h1 style="color: #F7F7F7; font-family: Varela Round;">Editing Friend</h1>
<br/>
<%= render "form", friend: @friend %>

<br>

<div>
  <%= link_to "Show this friend", @friend , class: "btn btn-primary"%> |
  <%= link_to "Back to friends", friends_path , class: "btn btn-primary"%>
</div>

app/views/friends/index.html.erb
<% if user_signed_in? %>

  <div class="tablerounededCorner">
    <table class="table table-bordered table-striped roundedTable">
      <thead class="table-dark">
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Phone</th>
        <th></th>
      </tr>
      </thead>
      <tbody>
      <% @friends.each do |friend| %>
        <% if friend.user == current_user %>
          <tr>
            <td>
              <%= link_to friend.first_name + ' ' + friend.last_name, friend %>
            <td><%= friend.email %></td>
            <td><%= friend.phone %></td>
            <td><%= button_to 'Delete', friend, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-outline-danger btn-sm" %></td>
          </tr>
        <% end %>
      <% end %>
      </tbody>
    </table>
  </div>

  <br>

  <%= link_to "New Friend", new_friend_path, class: "btn btn-secondary" %>
<% end %>
<%# else %>

<!--<h1>Hello World!</h1>-->

<%# end %>








<!--<p style="color: green"><%#= notice %></p>-->

<!--<h1>Friends</h1>-->

<!--<div id="friends">-->
<%# @friends.each do |friend| %>
<%#= render friend %>
<!--    <p>-->
<%#= link_to "Show this friend", friend %>
<!--    </p>-->
<%# end %>
<!--</div>-->

<%#= link_to "New friend", new_friend_path %>

app/views/friends/new.html.erb
<h1 style="color: #F7F7F7; font-family: Varela Round;">New friend</h1>
<br/>
<%= render "form", friend: @friend %>

<br>

<div style="font-family: Varela Round;">
  <%= link_to "Back to friends", friends_path, class: "btn btn-primary"%>
</div>

app/views/friends/show.html.erb
<section class="container mt-3">
  <div class="jumbotron px-3 py-4 px-sm-4 py-sm-5 bg-light rounded-3 mb-3">
    <h1 class="display-3" style="font-family: Varela Round;" ><%= @friend.first_name %> <%= @friend.last_name %></h1>
    <p class="lead">
      <%= @friend.email %> |
      <%= @friend.phone %>
    </p>
    <hr class="my-4">
    <%= link_to "Edit", edit_friend_path(@friend), class: "btn btn-primary" %>
    <%= link_to "Back", friends_path, class: "btn btn-secondary" %>
    <br/><br/>
    <%= button_to "Delete", @friend, method: :delete, class: "btn btn-danger"%>

  </div>
</section>

app/views/home/_header.html.erb
<header class="main-header">
  <div class="container">
    <nav class="navbar navbar-expand-lg main-nav px-0">
      <%= link_to image_tag("logo.svg", :alt => "rajeshdas.com", :size => "50x50"), root_path, class: "navbar-brand" %>
      <!--      <a class="navbar-brand" href="/mojo">-->
      <!--        <img src="http://rajeshdas.com/assets/images/logo.svg" alt="rajeshdas.com">-->
      <!--      </a>-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainMenu" aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
        <span class="icon-bar icon-bar-1"></span>
        <span class="icon-bar icon-bar-2"></span>
        <span class="icon-bar icon-bar-3"></span>
      </button>
      <div class="collapse navbar-collapse" id="mainMenu">
        <ul class="navbar-nav ml-auto text-uppercase f1">
          <li>
            <% if current_page?(root_path) %>
              <%= link_to "Home", root_path, class: "active active-first" %>
            <% else %>
              <%= link_to "Home", root_path %>
            <% end %>
          </li>
          <% if user_signed_in? %>
            <li>
              <% if current_page?(friends_path) %>
                <%= link_to "Friends", friends_path, class: "active active-first" %>
              <% else %>
                <%= link_to "Friends", friends_path %>
              <% end %>
            </li>
            <li>
              <% if current_page?(new_friend_path) %>
                <%= link_to "Add Friend", new_friend_path, class: "active active-first" %>
              <% else %>
                <%= link_to "Add Friend", new_friend_path %>
              <% end %>
            </li>
            <li>
              <% if current_page?(edit_user_registration_path) %>
                <%= link_to "Edit Profile", edit_user_registration_path, class: "active active-first" %>
              <% else %>
                <%= link_to "Edit Profile", edit_user_registration_path %>
              <% end %>
            </li>
            <li>
              <%= link_to "Sign Out", destroy_user_session_path %>
            </li>
          <% else %>
          <li>
            <% if current_page?(new_user_registration_path) %>
              <%= link_to "Sign Up", new_user_registration_path, class: "active active-first" %>
            <% else %>
              <%= link_to "Sign Up", new_user_registration_path %>
            <% end %>
          </li>
          <li>
            <% if current_page?(new_user_session_path) %>
              <%= link_to "Sign In", new_user_session_path, class: "active active-first" %>
            <% else %>
              <%= link_to "Sign In", new_user_session_path %>
            <% end %>
          </li>
          <% end %>
        </ul>
      </div>
    </nav>
  </div>
</header>

app/views/home/index.html.erb
<div class="blue-parent">
  <div class="blue-child"></div>
  <div class="blue-child"></div>
</div>

<br/><br/><br/>
<h1 class="header">Make Friends!</h1>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "header" %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" type="text/css" href="//fonts.googleapis.com/css?family=Varela+Round" />

  <title>Friends</title>
</head>
<body>
  <%= render "home/header" %>
  <br/><br/><br/><br/><br/>
  <div class="container">
    <%= yield %>
  </div>

<!-- Optional JavaScript; choose one of the two! -->

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

<!-- Option 2: Separate Popper and Bootstrap JS -->
<!--
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
-->
</body>
</html>